version: '3'

networks:
  users-system:

services:
  back-end:
    build:
      context: .
      dockerfile: node.dockerfile
    container_name: node-users-system
    ports:
      - "3333:3333"
    volumes:
      - ./node:/usr/src/users-system/node
    networks:
      - users-system

  front-end:
    build:
      context: .
      dockerfile: vue.dockerfile
    container_name: vue-users-system
    ports:
      - "3000:8080"
    volumes:
      - ./vue:/usr/src/users-system/vue
    networks:
      - users-system

  redis:
    image: "redis:latest"
    container_name: redis-users-system
    networks:
      - users-system

  mysql:
    build:
      context: .
      dockerfile: mysql.dockerfile
    container_name: mysql-users-system
    restart: always
    environment:
      MYSQL_DATABASE: 'usersSystem'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - users-system-db:/var/lib/mysql
    networks:
      - users-system
volumes:
  users-system-db: