services:
  back-end:
    build: node
    ports:
      - "3333:3333"
  redis:
    image: "redis:latest"
  mysql:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: 'userSystem'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
volumes:
  mysql-db: